version: '3'
services:
  qdrant-db:
    image: qdrant/qdrant:v1.7.1
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - app-net
  qdrant-client:
    build:
      dockerfile: docker/Dockerfile
      context: .
    depends_on:
      - qdrant-db
    volumes:
      - ./api:/app
    tty: true
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
    # # IPアドレス管理（IPAM）の設定
    # ipam:
    #   # IPAMドライバーを指定
    #   driver: default
    #   # ネットワークのサブネット設定
    #   config:
    #     - subnet: 172.25.1.0/24