version: '3'
services:
  qdrant-db:
    image: qdrant/qdrant:v1.7.1
    volumes:
      - db_data:/qdrant/storage
    networks:
      - app-net
  qdrant-client:
    build:
      dockerfile: docker/Dockerfile
      context: .
    depends_on:
      - qdrant-db
    volumes:
      - ./api:/app
    tty: true
    ports:
      - 5001:5000
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
    driver: bridge
